version: "3.8"

services:
    vault:
        image: 'vault'
        init: true
        container_name: 'vault-local'
        #exports work around vault bug https://github.com/hashicorp/vault/issues/3866
        #IP is the IP address of the default networking route
        #$$ escapes in "$" in docker-compose string interpolation
        command:
          - "sh"
          - "-c"
          - |
            set -ex
            export IP=$$(ip -o ro get $$(ip ro | awk '$$1 == "default" { print $$3 }') | awk '{print $$5}')
            export VAULT_API_ADDR="http://$${IP}:8200" VAULT_CLUSTER_ADDR="https://$${IP}:8201"
            mkdir -p /vault/data
            exec vault server -config=/vault/config
        environment:
          VAULT_ADDR: 'http://127.0.0.1:8200'
          VAULT_LOCAL_CONFIG: >-
              ui = true
              disable_mlock = true
              plugin_directory= "/vault/plugin"             
              storage "raft" {
                path    = "/vault/data"
                node_id = "node1"
              }
              listener "tcp" {
                address     = "0.0.0.0:8200"
                cluster_address = "0.0.0.0:8201"
                tls_disable = "true"
              }
              #disable_sealwrap = true # for Enterprise version
              #max_lease_ttl = "720h"
              #default_lease_ttl = "168h"

        cap_add:
          - IPC_LOCK
        network_mode: bridge
        ports:
            - "8200:8200"
            - "8201:8201"

        volumes:
            - ../build:/vault/plugin
            - ../script:/script
